### ISSUE TITLE
Browser extension display previous site credentials

### ISSUE THREAD

**Issue by manzing** [buttercup/buttercup-browser-extension#308] opened 2019-12-14 08:57 UTC
Hello,

I face a bug using Firefox extension since a long time now. I use webdav vault (on pcloud).
If i log in a website (let's say google) after starting my browser, it's fine, but if then i open a new tab and try to log into yahoo, when i click on buttercup icon at the right of the username field it displays google credentials.
I have to click another time on the buttercup button to "refresh" the credentials list to see the good one.
This is annoying as i usually don't pay attention to that so i try to login with wrong credentials on many websites.
This bug appeared  some months ago, it didn't occured in the past.
I have to say that i use many tabs and keep Firefox opened for several days.
I will try to disable some other extension and will update this report if necessary.
Did anyone face the same issue ?
Thanks

**Comment by perry-mitchell** [comment] 2019-12-25 10:01
Hi! This is a dupe of #283, and I'll close in favour of that one.. Sorry for the inconvenience.

**Closed by perry-mitchell** 2019-12-25 10:01 UTC
