### ISSUE TITLE
Fix incorrect form popup entry search suggestions #Bug #Enhancement #Question

### ISSUE THREAD

**Issue by ldexterldesign** [buttercup/buttercup-browser-extension#262] opened 2019-07-15 08:46 UTC
Hi all,

Hope you're well

Thanks for excellent software, as always

As title

I've been sitting on this annoying issue for a while, perhaps the past year because I suspected it may be OS/browser specific. I just reinstalled my OS hoping for resolution but no luck. Evident in Firefox too so I now suspect this is Buttercup (BC) specific...

When I load the BC form popup I get entry search suggestions matching the previously loaded tab

# Reproduce steps

See unexpected behaviour

# Unexpected behaviour (i.e. current)

1. Open browser
2. Navigate to website
3. Attempt to login - yields correct entry suggestion
4. Navigate to a new website
5. Repeat #3 - yields #3's entry search suggestion
6. Repeat #4
7. Repeat #3 - yields #5's entry search suggestion

# Expected behaviour

1. Open browser
2. Navigate to website
3. Attempt to login - yields correct entry suggestion
4. Navigate to a new website
5. Attempt to login - yields correct entry suggestion
6. Repeat #4
7. Attempt to login - yields correct entry suggestion

Screen cast: https://www.dropbox.com/sh/g1fmx7qqukhigiv/AABeLrWINOGVO6WmfqhS1Qgra

If you're reading and:

* agree, then please vote up (e.g. +1, like), or;
* disagree, then please vote down (e.g. -1, dislike) - I'd love to know why?

Welcome feedback/input

If you have any issues (e.g. questions/queries) then happy to help

Hope to hear back

Keep up sterling work!

Regards

hardware: Apple, MacBook Pro (Retina, 15-inch, Mid 2014)
software - operating system: Apple, macOS, 10.14.5 (18F132)
software - application: Buttercup, 1.16.0 (1.16.0)

**Comment by perry-mitchell** [comment] 2019-07-16 17:25
Hi @ldexterldesign - Thank you!

I've noticed this as well. I can't say where it appeared - we haven't modified the search logic and it appears to simply be a _delay_ in the processing. I don't recall offhand but I believe that when the dialog is open a call is made to update the results - this seems to happen to late and then the results don't refresh. Closing the dialog and then opening it again seems to fix it for me.

Definitely a bug, and one I intend on looking at in the very near future. I have additional features to add such as improved URL recognition, so this bug should hopefully get squashed then.

**Comment by reuterbal** [comment] 2019-07-17 07:45
I can confirm this on Ubuntu 16.04 and 18.04 using latest Firefox. The issue persists since at least a couple of months.

**Comment by aesthicc** [comment] 2019-07-17 17:32
Confirming this as well. The firefox extension first displays the last used entry when clicking the login form button, then the entry for the correct url on the second try.

**Comment by bigalgeorge** [comment] 2019-10-08 02:03
FF V69.0.1 popup and icons next to fields recall no previous entry/andor current url link to database.  I would expect it to perform as previous OP. The only way to get correct entry on my Elementary OS system is to enter keyfield and even that is not searching so well eg if I enter Kiwi I might get 2 Kiwi entries, then another random eg Experience (with no kiwi) then some more kiwi. When searching to be more accurate to the entered field. Perhaps some search options might help. Search/auto search/clipboard are effective for more complete search entry.

As aside; personal preference would be to do away with application and enhance web interface eg the after select vault interface to include search and editing functions.

**Comment by ldexterldesign** [comment] 2019-10-09 13:55
Hi @bigalgeorge,

> As aside; personal preference would be to do away with application and enhance web interface eg the after select vault interface to include search and editing functions.

I'd invite you to create a new issue for this if one doesn't already exist - I would be interested in discussion

Regards

**Comment by bigalgeorge** [comment] 2019-10-09 19:02
Done //ENHANCEMENT: Vault Interface to Web App

**Comment by ldexterldesign** [comment] 2019-10-09 20:25
https://github.com/buttercup/buttercup-browser-extension/issues/284

**Comment by perry-mitchell** [comment] 2019-10-12 11:22
On this topic: We're working on an improvement to searching for entries, so hopefully we'll get rid of this issue at the same time (seems to be a cross between state sync issues and bad matching logic (no fuzzy)).

**Comment by perry-mitchell** [comment] 2020-01-22 21:15
Will close in favour of #283.

**Closed by perry-mitchell** 2020-01-22 21:15 UTC
Labels: Priority: High, Status: Available, Type: Bug
