### ISSUE TITLE
[Bug] Login forms not detected

### ISSUE THREAD

**Issue by testsetse** [buttercup/buttercup-browser-extension#413] opened 2021-07-25 00:50 UTC
I've noticed that Buttercup fails to detect forms on some sites, [reddit](https://reddit.com), for example. This lefts us no option but to copy/paste the credentials manually.
![image](https://user-images.githubusercontent.com/24672231/126884262-0361c2c2-408a-4eed-ba9f-caa6acf1064c.png)

**Comment by perry-mitchell** [comment] 2021-08-06 20:12
Dupe of #374

**Closed by perry-mitchell** 2021-08-06 20:12 UTC
