### ISSUE TITLE
Failed connecting to 'webdav'resource on Firefox

### ISSUE THREAD

**Issue by ytilotti** [buttercup/buttercup-browser-extension#388] opened 2020-11-27 14:49 UTC
After a Buttercup installation on Windows & Mobile with the Webdav connector without problems, impossible to connect the webdav on Buttercup Firefox extension. Testing on Chrome is OK.

![Capture](https://user-images.githubusercontent.com/5848945/100460737-f8756380-30c7-11eb-96fa-e545942b755f.JPG)

Error message: 
![Capture2](https://user-images.githubusercontent.com/5848945/100460748-fd3a1780-30c7-11eb-8595-da586f108fec.JPG)

**Comment by perry-mitchell** [comment] 2020-11-27 20:08
Hmm, I'm not able to reproduce using my ownCloud or Yandex's Disk. What host are you using? OC or Nextcloud? Shouldn't the WebDAV URL be `/remote.php/webdav`?

**Comment by ytilotti** [comment] 2020-11-27 21:18
Nextcloud 20. Same error if change dav with webdav. But it's the URL on the Nextcloud.

Windows OK
Android OK
Chrome OK
Firefox KO

**Comment by chnoack** [comment] 2020-12-04 09:12
Hi,
I had similar problems. I can open the WebDAV vault in the Desktop App (Mac) and could open it in Firefox on my Mac, but not on my Linux: same error as above, except for "r is null".
Then I changed the password  in the Desktop App to see if this might help. Now I cannot open it in Firefox anymore.
on my Mac anyore. It reports a decryption error.

Very strange.

**Comment by perry-mitchell** [comment] 2020-12-06 14:36
Ok, I've bitten the bullet and decided to switch my home hosting from ownCloud -> Nextcloud. It'll take a bit to get set up but once it's going I'll do some more involved testing with bcup on it.

The error looks like a packaging issue - like some kind of library wasn't imported to do with WebDAV. This sounds mega strange as the build procedure for Chrome vs FF is mostly identical. It doesn't sound like it's related to Nextcloud (we have no NC specific code) but more likely just WebDAV.

**Comment by CTalvio** [comment] 2021-05-06 19:08
Did you find anything out? I am experiencing the exact same impasse as @ytilotti. I tried to work around it by setting Nextcloud to sync the database file onto my desktop, and using it as a local file. But that simply doesn't want to work, either. I can get the extension to connect to the desktop application, but when I navigate to the location of the local file to select it, it doesn't display anything, it's as if the folder is empty.

I tried entering the name of the file, as if making a new vault, but it just straight up overwrote it. Good thing I thought not to try that with my synced file.

As is, my only options left are dropbox and drive, which I won't use.

**Comment by situplastik** [comment] 2021-09-22 08:05
Similar issue here...

I connect Firefox (Developer Edition) with WebDAV vault, but every time that I restart the browser (or OS) the vault disappears :(

FF: 93.0
Buttercup extension: 2.24.3
os: OS X 11.5.2

**Comment by perry-mitchell** [comment] 2024-03-25 09:57
Closing this as the new V3 release renders this issue as either outdated or irrelevant. If you feel this was in error, please don't hesitate to comment. Please note that you should, at very least, test again in the new release once it's out.

**Closed by perry-mitchell** 2024-03-25 09:57 UTC
