### ISSUE TITLE
"Failed mapping credentials to a source" after updating to v2.15.0

### ISSUE THREAD

**Issue by danielbayerlein** [buttercup/buttercup-browser-extension#335] opened 2020-03-23 06:05 UTC
After updating the browser extension to version 2.15.0 it unfortunately does not work.

Error: `Failed mapping credentials to a source: Failed reading remote file`

Buttercup: `1.18.2`
Buttercup Browser Extension: `2.15.0`
Chrome: `80.0.3987.149`

![buttercup](https://user-images.githubusercontent.com/457834/77286907-9a8cb280-6cd4-11ea-947f-353a204f6b0c.png)

**Comment by danielbayerlein** [comment] 2020-03-27 06:35
@perry-mitchell Any idea?

**Comment by Li-An** [comment] 2020-04-08 21:19
Hello, it seems I have the same problem. If I open first the archive in Buttercup desktop, I can open after that the vault in browser (Win 10 64 bits and Centbrowser/Chrome)

**Comment by perry-mitchell** [comment] 2020-04-19 12:57
Hi, apologies for not seeing this issue. I suppose you may have given up, given the time without an answer - but in case you're still stuck perhaps you might tell us more details about how your environment is set up? Are you using the local file option in Buttercup browser?

If it is indeed a local file through buttercup, you should check Buttercup desktop's log files for information on why the file can't be read - the error is most likely occuring on the Buttercup desktop side.

**Comment by danielbayerlein** [comment] 2020-04-20 05:11
@perry-mitchell Correct, I'm using the local file option. The Buttercup Desktop log include no information.

* Buttercup Desktop:`1.19.0`
* Buttercup Browser Extension: `2.15.1`
* Chrome: `81.0.4044.113`
* macOS: `10.15.3`

**Comment by perry-mitchell** [comment] 2020-06-30 21:57
Released a new update for the local file option, which uses a revised edition of the connector. I tested it several times, locking and unlocking, saving, and it seemed to work. Please let me know if it still fails for you (v2.16.0).

**Comment by danielbayerlein** [comment] 2020-07-02 05:14
@perry-mitchell Unfortunately it still does not work.

Buttercup Desktop is closed:
```
Unable to unlock archive (6a39913f-96cc-4d83-b6d1-773c4d24af61): Unlocking archive source (6a39913f-96cc-4d83-b6d1-773c4d24af61) failed: Failed unlocking source: Failed to fetch
```

Buttercup Desktop is open:

```
Unable to unlock archive (6a39913f-96cc-4d83-b6d1-773c4d24af61): Unlocking archive source (6a39913f-96cc-4d83-b6d1-773c4d24af61) failed: Failed unlocking source: Failed reading remote file: /Users/dbayerlein/Documents/Tresor.bcup
```

Buttercup Desktop: `1.19.0`
Buttercup Browser Extension: `2.16.0`
Chrome: `83.0.4103.116`
macOS: `10.15.5`

**Comment by perry-mitchell** [comment] 2020-07-05 15:13
@danielbayerlein Please try re-adding the vault. I'm not able to reproduce this locally sorry. These local file connection issues have been tricky to diagnose as they're not easily reproduced between users.

**Comment by perry-mitchell** [comment] 2020-07-07 15:22
Closing for now. We can re-open if the issue is still present on current builds.

**Closed by perry-mitchell** 2020-07-07 15:22 UTC
