### ISSUE TITLE
Cannot unlock vault from browser extension v.2.10.0

### ISSUE THREAD

**Issue by ivanovd** [buttercup/buttercup-browser-extension#313] opened 2019-12-27 09:14 UTC
Since the new version I cannot unlock the vault from the browser ... it is just not showing the password field, just the change log.
<img width="695" alt="Annotation 2019-12-27 111352" src="https://user-images.githubusercontent.com/4889583/71511150-fa241f00-2899-11ea-95b9-ada00bb08ec3.png">

<img width="1914" alt="Annotation 2019-12-27 111556" src="https://user-images.githubusercontent.com/4889583/71511233-43746e80-289a-11ea-9d06-e7266bedce0f.png">

**Comment by Lipsch** [comment] 2019-12-27 09:28
@ivanovd you can still unlock vaults by navigation over the vaults dropdown:
![image](https://user-images.githubusercontent.com/1197665/71511702-8c74f480-2893-11ea-89a7-e1098dea0fba.png)

**Comment by vikaspotluri123** [comment] 2019-12-27 10:03
Duplicate of #312 😉

**Comment by ivanovd** [comment] 2019-12-27 10:12
@Lipsch thank you.
@vikaspotluri123 sorry, I was unable to find it before posting. Thanks for the hint. I will follow the other issue as well.

**Closed** 2019-12-27 10:12 UTC
