### ISSUE TITLE
Search results not updated for current URL

### ISSUE THREAD

**Issue by bigalgeorge** [buttercup/buttercup-browser-extension#283] opened 2019-10-08 02:23 UTC
Below shows Firefox 69.0.1 with no link to kiwibank item in database.
![Workspace 1_381](https://user-images.githubusercontent.com/6935387/66362318-bc240700-e9de-11e9-9778-98241cc5cef5.jpg)

below kiwibank is found only after typing 'kiwib' the entry 'experience...' has a username field with kiwi.... I dont think you should be searching usernames?
![Workspace 1_382](https://user-images.githubusercontent.com/6935387/66362488-7e73ae00-e9df-11e9-9019-23e2f89f21e2.jpg)

**Comment by perry-mitchell** [comment] 2019-10-10 19:46
Thanks @bigalgeorge - There are definitely improvements that are needed here. Currently working on a new system to perform fuzzy matching of URLs/domains, along with some basic memory of which profile was used where (popularity).

**Comment by bigalgeorge** [comment] 2019-10-13 00:56
OK I will sadly increase the urgency of this errant behaviour by adding the following:
First cut shows that co-operative.co.nz is in db. 
Second cut shows when arrived at this url (in Firefox 69) the dropdown shows vault has not searched on landed url. 
Expected behaviour: landed url item in vault should be first item shown (in case of unexpected form fill items then the copy/paste functions from dropdown menu item can be used).
![Selection_384](https://user-images.githubusercontent.com/6935387/66709461-1ba85b00-edc1-11e9-9315-2a771b480027.jpg)
![zzfdCZt6i4](https://user-images.githubusercontent.com/6935387/66709464-31b61b80-edc1-11e9-8493-cf6e3c50a3c8.jpg)

**Comment by perry-mitchell** [comment] 2019-10-16 17:37
Thanks @bigalgeorge - This is intermittent behaviour and I can't always reproduce it, making it a bit hard to debug and find a solution to. I'd be more than happy to review a PR if someone would take the time to investigate this further.

**Comment by bigalgeorge** [comment] 2019-10-16 20:03
Its looking a bit to me like the method you use to scan the url is getting confused by prepends+period on some urls eg
this url confuses: https://secure.bnz.co.nz
this url works: https://twitter.com/login

**Comment by perry-mitchell** [comment] 2019-10-21 16:52
Upon further investigation it was actually to do with [`componentWillMount `](https://github.com/buttercup/buttercup-browser-extension/blob/2702ecc3025bb0aa79e9a92b24c4e38651d51210/source/dialog/components/SearchPage.js#L18). This method is actually [deprecated](https://reactjs.org/docs/react-component.html#unsafe_componentwillmount) and should have been replaced. It's most likely _not_ firing which means the results are not updated upon opening the search dialog.

**Comment by perry-mitchell** [comment] 2020-01-08 15:31
Attempting a small patch in 2.11.1 - Not 100% sure if it fixes this, so please keep an eye out. It's working just file for me in development.

**Comment by perry-mitchell** [comment] 2020-01-24 18:51
Released 2.13.1 which has some search-level fixes.. Will be interesting to see if it has any effect on this issue.

**Comment by ldexterldesign** [comment] 2020-02-23 14:35
@perry-mitchell FYI issue still exists for me in v2.14

Regards

**Comment by perry-mitchell** [comment] 2020-02-23 17:07
Yep I can also still reproduce. Seems to be very stubborn. It seems to disappear during development but then.. returns in production. Any help would be appreciated..

**Comment by ldexterldesign** [comment] 2020-02-23 17:08
I'm in Vivaldi which browser are you using for production?

**Comment by perry-mitchell** [comment] 2021-05-22 18:40
Fixed.. Duplicated by #381

**Closed by perry-mitchell** 2021-05-22 18:40 UTC
Labels: Priority: High, Status: Available, Type: Bug

**Comment by ldexterldesign** [comment] 2021-05-22 23:43
@perry-mitchell Xmas came early 🤗

**Comment by perry-mitchell** [comment] 2021-05-23 13:18
@ldexterldesign Haha! It was a huge pain, this one.. Felt good to fix it finally!
