### ISSUE TITLE
Strange login bug Firefox and nextcloud with same user account

### ISSUE THREAD

**Issue by NodokaMurmevent** [buttercup/buttercup-browser-extension#165] opened 2018-08-31 08:25 UTC
Tested on : 
Firefox Dev 62 (Linux)
FF 61 (Linux and windows)

If i login with the browser i cannot connect on the cloud instance with buttercup,
It i logout from  the cloud instance i can connect the extention but if i login on the nextcloud after the browser prompt on each page a webauth login

the problem is only present if i use the same user on nexcloud and buttercup.

**Comment by Zjemm** [comment] 2018-08-31 09:39
i have the same issue with firefox

**Comment by NodokaMurmevent** [comment] 2018-08-31 09:49
if anybody need a temporary solution you can use this app 
https://apps.nextcloud.com/apps/groupfolders
create a new group "buttercupuser"
create a new user "buttercup"
add your user and the new user on the group "buttercupuser"
Create a shared group folder for "buttercupuser" and move your database in the new folder
Finally remove you database in the extension and do a new connection with the user "buttercup"

**Comment by perry-mitchell** [comment] 2018-09-07 10:18
It's possible that this is due to some cookie/session problem with being logged in. Historically there have been issues with ownCloud/Nextcloud sessions causing problems with WebDAV access. I don't unfortunately have the time to debug this right now, as I only have ownCloud at home. I'll update my instance and will hopefully be able to check this soon - Nextcloud is downstream so hopefully any incompatibilities are reproducible in ownCloud also.

**Comment by reuterbal** [comment] 2020-04-08 09:48
For a possible workaround that is less invasive than the groupfolders solution: https://github.com/buttercup/buttercup-browser-extension/issues/222#issuecomment-610859718

**Comment by perry-mitchell** [comment] 2024-03-25 19:54
Closing this as the new V3 release renders this issue as either outdated or irrelevant. If you feel this was in error, please don't hesitate to comment. Please note that you should, at very least, test again in the new release once it's out.

**Closed by perry-mitchell** 2024-03-25 19:54 UTC
Labels: Type: Bug, Status: Pending
