### ISSUE TITLE
Firefox components can't connect to each other

### ISSUE THREAD

**Issue by morojgovany** [buttercup/buttercup-browser-extension#102] opened 2018-01-19 09:59 UTC
Hi,
I have a problem with the browser extension buttercup, in firefox (developper edition and ESR) and Vivaldi. In firefox (both editions) I can add an archive and unlock it, all is fine but if I close & restart firefox, the archives just disappeared and I have to add it again like new ones.
With vivaldi, no problem to unlock or keep the archives between sessions, but buttercup can't see the credentials in my archive...
Chrome extension is working fine.
I took screenshots with chrome and vivaldi to compare :

VIVALDI :
![vivaldi_issue](https://user-images.githubusercontent.com/24272862/35144720-ab54dd7c-fd05-11e7-8cf0-71dc858b32c1.png)

CHROME:
![chrome_buttercup](https://user-images.githubusercontent.com/24272862/35144721-abc49504-fd05-11e7-9966-a64d1085c559.png)

Am I missing something  ?
My conf : "Debian GNU/Linux 9.3 (stretch) / Firefox ESR 52.5.2 / Firefox developper edition 59.0b1 / Vivaldi 1.13.1008.40 (Stable channel) (64 bits) / Chrome 63.0.3239.132"

Thanks !

**Comment by perry-mitchell** [comment] 2018-01-20 09:37
Unfortunately version 1.* of the extension is not supported on Firefox yet. It hasn't been released yet, so I'm not sure why you're running it 😅

There are some issues in the inter-tab/background communication that will prevent the extension from working properly currently. Once they're fixed and it's officially released for Firefox, we should revisit this..

**Comment by perry-mitchell** [comment] 2018-01-20 16:06
Blocked by #104

**Comment by perry-mitchell** [comment] 2018-01-20 21:31
Hi @morojgovany - Could you please install version 1.0.4 from the store in Firefox to confirm if the issue is gone or not? This is our first official release for Firefox.

Please note that we do not currently support vivaldi.

**Comment by morojgovany** [comment] 2018-01-21 10:17
I installed the new version on firefox and it cumulates the vivaldi bug with the firefox's. I can add an archive but unable to read something in it, if I close and restart the archive disappeared again. 

![capture d ecran de 2018-01-21 11-08-28](https://user-images.githubusercontent.com/24272862/35193006-8da1f772-fe9c-11e7-96a2-39f17443d2c7.png)


Thanks for your quick answer and your great app.

**Comment by perry-mitchell** [comment] 2018-01-21 12:58
Good point - Thanks for clarifying @morojgovany I can reproduce this now:

![image](https://user-images.githubusercontent.com/3869469/35194384-8bf8245e-febb-11e7-84ab-344ebf32f386.png)

**Comment by perry-mitchell** [comment] 2018-01-21 14:28
Seems to be an issue with permissions:

![image](https://user-images.githubusercontent.com/3869469/35195160-10696f20-fec8-11e7-86ed-073a1b6077f2.png)

With this method coming from the dialog section:

![image](https://user-images.githubusercontent.com/3869469/35195162-1d773ab2-fec8-11e7-98fa-bf3d44b0ba29.png)

Very strange seeing as the dialog is in an iframe..

**Comment by perry-mitchell** [comment] 2018-01-21 17:36
This should hopefully have been resolved by #107 - I won't close until we confirm.

**Comment by perry-mitchell** [comment] 2018-01-21 17:57
> if I close and restart the archive disappeared again.

I can't see the archive disappearing when I restart on 1.0.6. Killing Firefox and restarting it, the archive appears in the list as locked (as intended).

**Comment by morojgovany** [comment] 2018-01-23 12:35
Ok I found, it's due to my firefox settings : 

accept cookies > from visited websites
keep until > I close firefox
clean history when firefox closes > cache / active connexions / cookies

I can now use buttercup easily ! :+1: : 
Hope it helps

**Comment by julianpoemp** [comment] 2018-01-24 09:19
I have the same problem. When I close Firefox and open it again, the archive is lost. I don't want to deselect the "clear history when firefox closes" option because of security reasons. Is there any hope that this bug can be fixed so that we do not have to deselect this option?

The Android app in connection to owncloud does not work for me, too. [https://github.com/buttercup/buttercup-mobile/issues/76](url)

**Comment by perry-mitchell** [comment] 2018-01-24 09:33
> the "clear history when firefox closes" option

It *may* be possible to get around this by modifying the storage section of the extension.. Probably changing it to the dedicated browser storage could help here.

> The Android app in connection to owncloud does not work for me, too. 

Let's discuss that in the other issue :)

**Comment by julianpoemp** [comment] 2018-01-24 09:35
> It may be possible to get around this by modifying the storage section of the extension.. Probably changing it to the dedicated browser storage could help here.

That would be awesome! Nice work by the way! The extension is very easy to use.

**Comment by perry-mitchell** [comment] 2018-01-24 09:36
Seeing as the component communication is done, I'll close this in favour of #109.

**Closed by perry-mitchell** 2018-01-24 09:36 UTC
Labels: Priority: High, Status: Completed, Type: Bug
