### ISSUE TITLE
Password autocomplete appearing in unrelated fields

### ISSUE THREAD

**Issue by Gkupce** [buttercup/buttercup-browser-extension#479] opened 2024-03-27 21:48 UTC
On Firefox the extension seems to be triggering on search fields

On github
![image](https://github.com/buttercup/buttercup-browser-extension/assets/6500411/be769baf-f164-4d1a-915d-d4c3ef3ceefe)

On youtube
![image](https://github.com/buttercup/buttercup-browser-extension/assets/6500411/401a8898-1117-43b0-8d3e-2d1ac5966815)

DuckDuckGo
![image](https://github.com/buttercup/buttercup-browser-extension/assets/6500411/f9429205-4f5d-4d3c-8683-e6204df193a8)

At https://www.dyslexic-charactersheets.com/build/pathfinder
![image](https://github.com/buttercup/buttercup-browser-extension/assets/6500411/9a0fe9c7-4366-49ca-accd-bc67cc293290)

I have yet to verify but for some reason it seems to be triggering on any normal text field

Firefox 121.0 (64-bit) for fedora
Nobara linux

**Comment by perry-mitchell** [comment] 2024-03-28 05:02
Dupe of #469

**Closed** 2024-03-28 05:02 UTC
