### ISSUE TITLE
unable to unlock vault

### ISSUE THREAD

**Issue by marafa** [buttercup/buttercup-browser-extension#317] opened 2020-01-10 03:21 UTC
just installed buttercup-desktop. gave it the proper google drive permissions. created a vault on gdrive.
installed the browser extension for ff and chrome 
then while the desktop version is open i tried to use the extension. this is what i see
![Screenshot_20200109_221351](https://user-images.githubusercontent.com/1518315/72122862-6d637180-332d-11ea-9fc0-cc609ac7c7a4.png)

**Comment by dasheck0** [comment] 2020-01-10 09:04
+1

**Comment by perry-mitchell** [comment] 2020-01-10 21:34
Works fine for me in the latest version on Firefox:

![image](https://user-images.githubusercontent.com/3869469/72187705-1929c180-3401-11ea-9427-3128f9750214.png)

and Chrome:

![image](https://user-images.githubusercontent.com/3869469/72187819-5e4df380-3401-11ea-8ddb-3c26a382213d.png)

Chrome's version is lagging behind the latest by one patch version, but this doesn't affect the login prompt.

Are there any other details you can provide? Anything special with your environment you're running? What happens if you restart the browser?

We'd need some way to reproduce this so if you can think of anything that might help. Having the desktop open or closed at this stage has not effect as the browser extension will _only_ contact it in the event of a local file vault being unlocked.

**Comment by marafa** [comment] 2020-01-10 22:27
this is what i just did
1. ran buttercup-desktop
1. unlocked my vault
1. started firefox and chrome ( i have both extensions installed)
1. clicked on the extension icon .. same picture

**Comment by jsbeckr** [comment] 2020-01-11 17:51
Doesn't work for me either.

Buttercup Desktop 1.18.2 (from Homebrew)
Buttercup Chrome Extension 2.11.0

macOS Catalina

**Comment by Peppeo** [comment] 2020-01-15 02:03
![Screen Shot 2020-01-15 at 8 53 56 AM 2](https://user-images.githubusercontent.com/53419266/72398218-38468d00-373a-11ea-9680-5171d5e4f40e.png)
Well, definitely have a similar type of problem on both Chrome and Firefox and macOS. This is what I see after: 1. freshly installing the extension 2. giving permission to Buttercup to access my Drive 3. and then looking for the vault on Google Drive. I am not able to browse Drive anymore.

**Comment by Peppeo** [comment] 2020-01-15 02:04
![Screen Shot 2020-01-15 at 9 00 34 AM](https://user-images.githubusercontent.com/53419266/72398544-316c4a00-373b-11ea-9a44-8b880c39aac3.png)
![Screen Shot 2020-01-15 at 8 59 19 AM](https://user-images.githubusercontent.com/53419266/72398545-3204e080-373b-11ea-9850-ab8b6eb2d3d9.png)
As you can see the desktop application can actually connect to Drive and connect to the proper vault. For the time being I downloaded a vault locally and connected to that in the respective browsers.

**Comment by perry-mitchell** [comment] 2020-01-18 15:11
> I am not able to browse Drive anymore.
@Peppeo We removed the global permissions for google drive as they were too open. Many users were not wanting to use the feature due to the overly permissive rights Buttercup had on contents in their drive.

This is the safer, more generally accepted method. You can access only files that have been created by Buttercup or accessed earlier. Uploading vaults won't work. We will add support for importing buttercup vaults soon so you can add an existing one to drive.

**Comment by perry-mitchell** [comment] 2020-01-18 16:52
I'll close this for now - there's several issues being discussed here now which isn't helping. @marafa that is a styling issue you were originally seeing - if it's still occuring and there's some way you could show the contents of your console, we could perhaps reopen or readdress this in some other way. Browsers being mostly the same across OSes though, it shouldn't be an OS-specific issue. I suspect that running the latest version should allow you to login without issue.

**Closed by perry-mitchell** 2020-01-18 16:52 UTC
