### ISSUE TITLE
Save-new-credentials fails to save

### ISSUE THREAD

**Issue by tourtools** [buttercup/buttercup-browser-extension#352] opened 2020-07-23 16:13 UTC
on Brave 1.11.97 (84.0.4147.89) after ButterCup update to 2.18.0 when trying to save new credentials it gets stuck with the loading gif and the overlay and, as collateral problem, the extension CPU usage get go to the top.

**Comment by tourtools** [comment] 2020-07-23 16:14
Same behaviour occurring to my colleague on Firefox latest version.

**Comment by LividJava** [comment] 2020-07-23 23:29
#253

**Comment by perry-mitchell** [comment] 2020-07-25 14:33
@tourtools What vault type are you using? I've been testing with WebDAV and Dropbox on Brave, using 2.18.0, with no issue. New entries are saved and persist.

**Comment by tourtools** [comment] 2020-07-25 14:40
@perry-mitchell I do have Dropbox vaults (2 vaults)

**Comment by perry-mitchell** [comment] 2020-08-23 17:24
Is this still present on 2.20.2?

**Comment by perry-mitchell** [comment] 2020-08-24 19:16
@tourtools I'm closing this as I just tested a couple of dropbox vaults on current brave with the latest extension version (2.20.2), and didn't see any issue. There were substantial performance issues fixed in this version, so please update and try again.

**Comment by tourtools** [comment] 2020-08-24 20:52
sorry @perry-mitchell I'm in a place where the internet connection is slow by nature, so I can't check it, but I think there's no problem in closing it, asap I'll check it.

thanks,

**Comment by ldexterldesign** [comment] 2020-09-30 02:08
I would reopen this issue because it's failing for me

<img width="1860" alt="Screenshot 2020-09-30 at 02 55 10" src="https://user-images.githubusercontent.com/1715809/94634612-6409a300-02c8-11eb-82e0-ffed8dc92b00.png">

Will try investigate further to see if it's browser specific or the fact I'm using Dropbox with Boxcryptor...

Hope this helps

Sincerely

**Comment by perry-mitchell** [comment] 2020-10-04 12:21
Thanks @ldexterldesign! If you find a way to reproduce that'd be great! I haven't yet seen this issue, but I'll reopen.

**Comment by ldexterldesign** [comment] 2020-11-21 01:29
FYI working fine for me tonight

Apologies

**Closed** 2020-11-21 13:36 UTC
Labels: Status: Needs reproduction, Type: Bug
