### ISSUE TITLE
Feature Request: never lock vault on browser restart

### ISSUE THREAD

**Issue by arnnis** [buttercup/buttercup-browser-extension#443] opened 2023-01-05 09:38 UTC
This feature will greatly improve the user experience, as typing in a password every  time can be inconvenient. 

Bitwarden has this feature.

**Comment by perry-mitchell** [comment] 2023-02-12 20:51
@arnnis Any idea how it's implemented? Right now I can't think of a way besides either saving the user's password in storage or some other secret value.. which strikes me as insecure. I'd be all for this feature if there was some way to achieve it securely.

**Comment by perry-mitchell** [comment] 2023-02-12 20:52
Dupe of #292

**Closed by perry-mitchell** 2023-02-12 20:52 UTC
