### ISSUE TITLE
Managing vaults: new entry never been saved

### ISSUE THREAD

**Issue by snakewa** [buttercup/buttercup-browser-extension#253] opened 2019-05-15 01:16 UTC
In chrome v2.7.0, in Managing vault interface, add new entry never been saved. It is said successfully saved in green notification, but Cmd+R refresh the page, the entry will be gone.  but edit exiting entries from Desktop or save from login form is ok

**Comment by perry-mitchell** [comment] 2019-05-19 18:21
Confirmed - I can see that the entry isn't saved.. Thanks @snakewa

**Comment by Temurson** [comment] 2019-08-10 22:25
Is it already fixed? I am still experiencing this issue in using the Chrome extension v2.8.0. I am storing my vault in Dropbox. When I add any kind of entry using the extension, it is not being saved (just as in description above).

**Comment by jokeyrhyme** [comment] 2019-08-15 00:28
@Temurson yeah, I don't think v2.8.0 on Firefox is saving to the vault persistently, either
I have to use the Windows / macOS desktop version of Buttercup to achieve this for now

**Comment by perry-mitchell** [comment] 2019-08-23 14:34
I tested it and it worked when releasing, so not sure what might be happening. I'll try to confirm it again, with dropbox, as soon as I can.

**Comment by jokeyrhyme** [comment] 2019-08-23 23:49
I was saving to Dropbox and it wasn't working, although the toast/notification thing in the top-right would say that it was saved
Is it possible that the toast is popping up before it is finished? Maybe I"m closing the window too quickly...

**Comment by perry-mitchell** [comment] 2019-08-31 20:26
Ok, I can confirm that this has returned ☹️

It affects all datasource types, too.

**Closed** 2019-09-01 12:33 UTC
Labels: Priority: Critical, Status: Available, Type: Bug

**Comment by perry-mitchell** [comment] 2019-09-01 12:35
Ok, finally found the issue. The UI library was providing a UUID to new blank entry IDs, which it shouldn't do, when it's new. The facade library (which maps changes back to vaults after editing them in the manage-vault section) was mistakenly thinking it was an existing entry when it wasn't.

**Comment by perry-mitchell** [comment] 2019-09-01 12:50
Released the fix in 2.8.1.

**Comment by ErdeFB** [comment] 2019-10-15 04:59
I'm getting this same error when I tried saving to my db that I exported from LastPass in the CVS format. As stated above, when using a newly created vault this error does not occur. It is weird since I can read the vault trough the extension, but not save to it.

**Comment by LividJava** [comment] 2020-07-18 18:25
2.18.0 seems to have this issue come back up?? not certain if this is reproducible (Firefox 79 Dev edition)

**Comment by jokeyrhyme** [comment] 2020-07-18 20:16
I saved an entry using the vault manager interface (not the flow starting from the top-right in-page pop-up) yesterday with Firefox 78 and Buttercup extension 2.18.0 combined with the Google Drive backend, and I can confirm that it did persist the changes correctly: other devices can view the new value when connecting to the same backend via Buttercup

@LividJava which flow did you use? Starting from the vault manager interface? Or from the top-right in-page pop-up? And which storage backend are you using? Is it possible that you closed Firefox before the changes were properly persisted (I'm not sure if Buttercup's progress/activity indicators represent the full amount of work required)?

**Comment by tourtools** [comment] 2020-07-22 22:35
same behaviour with 2.18.0 and the last version of Brave (chromium)

**Comment by LividJava** [comment] 2020-07-23 19:40
> 
> 
> I saved an entry using the vault manager interface (not the flow starting from the top-right in-page pop-up) yesterday with Firefox 78 and Buttercup extension 2.18.0 combined with the Google Drive backend, and I can confirm that it did persist the changes correctly: other devices can view the new value when connecting to the same backend via Buttercup
> 
> @LividJava which flow did you use? Starting from the vault manager interface? Or from the top-right in-page pop-up? And which storage backend are you using? Is it possible that you closed Firefox before the changes were properly persisted (I'm not sure if Buttercup's progress/activity indicators represent the full amount of work required)?

My vaults usually just disappear after restarting my browser, using either flow, and i have a local bcup file for my backend storage
